---
# git_url: <repo>
git_key: ''
git_branch: 'master'
git_msg: 'update files with ansible'
# git_push_tag: v1 # optional tag for commit
# git_pull_tag: v1 # optional tag for commit
# git_changelog: CHANGELOG.md # optional path to changelog
git_remove_local: false
git_username: ansible_git
git_email: ansible_git@ansible.com 